apiVersion: apps/v1
kind: Deployment
metadata:
  name: ab-capstone-project

spec:
  replicas: 1
  selector:
    matchLabels:
      app: ab-capstone-project
  template:
    metadata:
      labels:
        app: ab-capstone-project
    spec:
      containers:
        - name: ab-capstone-project
          image: abhibhatia/my-first-react-image
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "64Mi"
              cpu: "500m"
