apiVersion: v1
kind: Service
metadata:
  name: capstone-udacity
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
  namespace: default
  labels:
    app: capstone-udacity
spec:
  selector:
    app: capstone-udacity
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-udacity
  namespace: default
  labels:
    app: capstone-udacity
spec:
  replicas: 3
  selector:
    matchLabels:
      app: capstone-udacity
  template:
    metadata:
      labels:
        app: capstone-udacity
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: capstone-udacity
        image: public.ecr.aws/d1i9z8s6/abcapstone
        ports:
        - containerPort: 80