apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-test
spec:
  selector:
    matchLabels:
      app: reactapp-test
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: reactapp-test
    spec:
      containers:
        - name: reactapp-test
          image: abhibhatia/hubreactapp1
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: reactapp-test
spec:
  type: LoadBalancer
  selector:
    app: reactapp-test
  ports:
    -port: 80
    targetPort: 80
    nodePort: 30000