apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-prod
spec:
  selector:
    matchLabels:
      app: greenreactapp
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: greenreactapp
    spec:
      containers:
        - name: greenreactapp
          image: abhibhatia28/testreact
          ports:
            - containerPort: 80